export interface DataType {
  id: number;
  city: string;
  address: string;
  price: number;
  room: number;
  bed: number;
  bathroom: number;
  area: number;
}

export const hotelData: DataType[] = [
  {
    id: 1,
    city: "New York",
    address: "2333 Union Alley",
    price: 5753,
    room: 2,
    bed: 6,
    bathroom: 2,
    area: 848,
  },
  {
    id: 2,
    city: "Mumbai",
    address: "9031 Dryden Avenue",
    price: 5360,
    room: 4,
    bed: 4,
    bathroom: 2,
    area: 758,
  },
  {
    id: 3,
    city: "Paris",
    address: "71 Graceland Place",
    price: 9580,
    room: 3,
    bed: 3,
    bathroom: 2,
    area: 757,
  },
  {
    id: 4,
    city: "London",
    address: "98409 Roth Court",
    price: 7046,
    room: 1,
    bed: 6,
    bathroom: 3,
    area: 661,
  },
  {
    id: 5,
    city: "New York",
    address: "24288 Springview Street",
    price: 5952,
    room: 2,
    bed: 6,
    bathroom: 1,
    area: 771,
  },
  {
    id: 6,
    city: "Mumbai",
    address: "88931 Mandrake Avenue",
    price: 7529,
    room: 1,
    bed: 2,
    bathroom: 2,
    area: 989,
  },
  {
    id: 7,
    city: "Paris",
    address: "464 Meadow Ridge Alley",
    price: 6355,
    room: 1,
    bed: 3,
    bathroom: 2,
    area: 556,
  },
  {
    id: 8,
    city: "London",
    address: "21 Old Shore Way",
    price: 6959,
    room: 2,
    bed: 3,
    bathroom: 1,
    area: 630,
  },
  {
    id: 9,
    city: "New York",
    address: "855 Rockefeller Parkway",
    price: 6389,
    room: 3,
    bed: 3,
    bathroom: 2,
    area: 836,
  },
  {
    id: 10,
    city: "Mumbai",
    address: "6 Shoshone Road",
    price: 6410,
    room: 1,
    bed: 3,
    bathroom: 2,
    area: 990,
  },
  {
    id: 11,
    city: "Paris",
    address: "4895 Village Drive",
    price: 7133,
    room: 2,
    bed: 4,
    bathroom: 1,
    area: 512,
  },
  {
    id: 12,
    city: "London",
    address: "9882 Ryan Trail",
    price: 6317,
    room: 1,
    bed: 5,
    bathroom: 2,
    area: 571,
  },
  {
    id: 13,
    city: "New York",
    address: "5501 Dapin Drive",
    price: 8532,
    room: 2,
    bed: 2,
    bathroom: 2,
    area: 804,
  },
  {
    id: 14,
    city: "Mumbai",
    address: "95 Sugar Drive",
    price: 8981,
    room: 2,
    bed: 2,
    bathroom: 1,
    area: 632,
  },
  {
    id: 15,
    city: "Paris",
    address: "7272 Sachtjen Court",
    price: 8256,
    room: 1,
    bed: 4,
    bathroom: 3,
    area: 643,
  },
  {
    id: 16,
    city: "London",
    address: "68 Eagan Hill",
    price: 8246,
    room: 1,
    bed: 2,
    bathroom: 2,
    area: 626,
  },
  {
    id: 17,
    city: "New York",
    address: "36951 Farmco Way",
    price: 6054,
    room: 2,
    bed: 6,
    bathroom: 3,
    area: 567,
  },
  {
    id: 18,
    city: "Mumbai",
    address: "10550 Magdeline Point",
    price: 5576,
    room: 1,
    bed: 4,
    bathroom: 3,
    area: 604,
  },
  {
    id: 19,
    city: "Paris",
    address: "123 Cardinal Center",
    price: 9392,
    room: 4,
    bed: 2,
    bathroom: 2,
    area: 964,
  },
  {
    id: 20,
    city: "London",
    address: "53 Lukken Drive",
    price: 8008,
    room: 2,
    bed: 5,
    bathroom: 2,
    area: 694,
  },
  {
    id: 21,
    city: "New York",
    address: "5 Fremont Park",
    price: 7855,
    room: 2,
    bed: 3,
    bathroom: 1,
    area: 626,
  },
  {
    id: 22,
    city: "Mumbai",
    address: "40406 Meadow Vale Avenue",
    price: 6384,
    room: 1,
    bed: 3,
    bathroom: 2,
    area: 612,
  },
  {
    id: 23,
    city: "Paris",
    address: "6 Alpine Circle",
    price: 6189,
    room: 2,
    bed: 2,
    bathroom: 2,
    area: 566,
  },
  {
    id: 24,
    city: "London",
    address: "9 Oxford Place",
    price: 6895,
    room: 1,
    bed: 3,
    bathroom: 3,
    area: 966,
  },
  {
    id: 25,
    city: "New York",
    address: "9 Fisk Court",
    price: 5336,
    room: 3,
    bed: 2,
    bathroom: 2,
    area: 858,
  },
  {
    id: 26,
    city: "Mumbai",
    address: "20 Roth Trail",
    price: 5608,
    room: 4,
    bed: 2,
    bathroom: 3,
    area: 635,
  },
  {
    id: 27,
    city: "Paris",
    address: "267 Birchwood Terrace",
    price: 6347,
    room: 3,
    bed: 4,
    bathroom: 3,
    area: 879,
  },
  {
    id: 28,
    city: "London",
    address: "80 Miller Plaza",
    price: 9155,
    room: 2,
    bed: 4,
    bathroom: 3,
    area: 663,
  },
  {
    id: 29,
    city: "New York",
    address: "05441 Service Park",
    price: 6927,
    room: 3,
    bed: 4,
    bathroom: 1,
    area: 570,
  },
  {
    id: 30,
    city: "Mumbai",
    address: "39460 Spaight Circle",
    price: 8168,
    room: 3,
    bed: 2,
    bathroom: 1,
    area: 589,
  },
  {
    id: 31,
    city: "Paris",
    address: "628 Miller Place",
    price: 8404,
    room: 3,
    bed: 4,
    bathroom: 3,
    area: 998,
  },
  {
    id: 32,
    city: "London",
    address: "675 Stone Corner Center",
    price: 5853,
    room: 2,
    bed: 3,
    bathroom: 2,
    area: 540,
  },
  {
    id: 33,
    city: "New York",
    address: "2 Meadow Valley Court",
    price: 5532,
    room: 2,
    bed: 4,
    bathroom: 2,
    area: 578,
  },
  {
    id: 34,
    city: "Mumbai",
    address: "6 Basil Parkway",
    price: 8484,
    room: 3,
    bed: 2,
    bathroom: 2,
    area: 742,
  },
  {
    id: 35,
    city: "Paris",
    address: "83 Anzinger Lane",
    price: 8110,
    room: 4,
    bed: 3,
    bathroom: 3,
    area: 756,
  },
  {
    id: 36,
    city: "London",
    address: "77 Westridge Terrace",
    price: 9898,
    room: 2,
    bed: 2,
    bathroom: 1,
    area: 701,
  },
  {
    id: 37,
    city: "New York",
    address: "950 Derek Crossing",
    price: 7636,
    room: 4,
    bed: 6,
    bathroom: 3,
    area: 960,
  },
  {
    id: 38,
    city: "Mumbai",
    address: "4 Ilene Trail",
    price: 10000,
    room: 1,
    bed: 4,
    bathroom: 3,
    area: 591,
  },
  {
    id: 39,
    city: "Paris",
    address: "4936 Sheridan Street",
    price: 9710,
    room: 4,
    bed: 2,
    bathroom: 2,
    area: 631,
  },
  {
    id: 40,
    city: "London",
    address: "1 Stone Corner Pass",
    price: 7144,
    room: 2,
    bed: 2,
    bathroom: 2,
    area: 694,
  },
  {
    id: 41,
    city: "New York",
    address: "4 Texas Court",
    price: 5244,
    room: 1,
    bed: 5,
    bathroom: 3,
    area: 718,
  },
  {
    id: 42,
    city: "Mumbai",
    address: "1 Becker Pass",
    price: 8310,
    room: 3,
    bed: 2,
    bathroom: 1,
    area: 580,
  },
  {
    id: 43,
    city: "Paris",
    address: "5 Del Mar Court",
    price: 9998,
    room: 2,
    bed: 2,
    bathroom: 1,
    area: 943,
  },
  {
    id: 44,
    city: "London",
    address: "06064 Dryden Crossing",
    price: 9730,
    room: 3,
    bed: 6,
    bathroom: 2,
    area: 893,
  },
  {
    id: 45,
    city: "New York",
    address: "75029 Alpine Court",
    price: 8341,
    room: 1,
    bed: 3,
    bathroom: 2,
    area: 559,
  },
  {
    id: 46,
    city: "Mumbai",
    address: "258 American Avenue",
    price: 8354,
    room: 3,
    bed: 2,
    bathroom: 3,
    area: 826,
  },
  {
    id: 47,
    city: "Paris",
    address: "4880 Ramsey Terrace",
    price: 8379,
    room: 3,
    bed: 6,
    bathroom: 1,
    area: 795,
  },
  {
    id: 48,
    city: "London",
    address: "0 Lakewood Gardens Court",
    price: 8685,
    room: 1,
    bed: 5,
    bathroom: 2,
    area: 593,
  },
  {
    id: 49,
    city: "New York",
    address: "4 Morning Avenue",
    price: 8449,
    room: 1,
    bed: 6,
    bathroom: 2,
    area: 761,
  },
  {
    id: 50,
    city: "Mumbai",
    address: "95534 Surrey Parkway",
    price: 5627,
    room: 1,
    bed: 4,
    bathroom: 1,
    area: 686,
  },
  {
    id: 51,
    city: "Paris",
    address: "4 Chive Way",
    price: 5371,
    room: 1,
    bed: 2,
    bathroom: 1,
    area: 759,
  },
  {
    id: 52,
    city: "London",
    address: "1 Huxley Crossing",
    price: 7214,
    room: 2,
    bed: 6,
    bathroom: 3,
    area: 622,
  },
  {
    id: 53,
    city: "New York",
    address: "9 Moose Circle",
    price: 8900,
    room: 4,
    bed: 6,
    bathroom: 3,
    area: 790,
  },
  {
    id: 54,
    city: "Mumbai",
    address: "47 American Ash Trail",
    price: 5533,
    room: 2,
    bed: 6,
    bathroom: 3,
    area: 589,
  },
  {
    id: 55,
    city: "Paris",
    address: "59092 Monica Way",
    price: 6046,
    room: 4,
    bed: 6,
    bathroom: 2,
    area: 884,
  },
  {
    id: 56,
    city: "London",
    address: "8 Dennis Circle",
    price: 9793,
    room: 4,
    bed: 4,
    bathroom: 3,
    area: 774,
  },
  {
    id: 57,
    city: "New York",
    address: "8 Grayhawk Road",
    price: 6617,
    room: 4,
    bed: 5,
    bathroom: 3,
    area: 576,
  },
  {
    id: 58,
    city: "Mumbai",
    address: "9719 Springview Street",
    price: 5935,
    room: 1,
    bed: 6,
    bathroom: 3,
    area: 921,
  },
  {
    id: 59,
    city: "Paris",
    address: "6 Pawling Pass",
    price: 7077,
    room: 2,
    bed: 2,
    bathroom: 1,
    area: 581,
  },
  {
    id: 60,
    city: "London",
    address: "664 Morning Circle",
    price: 5241,
    room: 4,
    bed: 6,
    bathroom: 1,
    area: 708,
  },
];
